@urlshortener_HostAddress = http://localhost:5163

POST {{urlshortener_HostAddress}}/shorten
Content-Type: application/json
Cache-Control: no-cache

{
    "longUrl": "http://localhost:8080/test5"
}

###

GET {{urlshortener_HostAddress}}/iGJYCreqm HTTP/1.1
Content-Type: application/json
