pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/dotnet/sdk:8.0'
        }
    }

    stages {
        stage('Install dependencies'){
            steps {
                sh 'apt-get update \
                    && apt-get install -y build-essential \
                    && echo "Done installing dependencies"'
            }
        }

        stage('Run Tests'){
            steps{
                dir('urlShortener'){
                    sh 'make test'
                }
            }
        }

        stage('Build images'){
            steps{
                dir('urlShortener'){
                    sh 'make build-images'
                }
            }
        }
    }
}