pipeline {
    agent any
    stages {
        stage('Run Tests'){
            agent { docker {image 'mcr.microsoft.com/dotnet/sdk:8.0'}}
            steps{    
                dir('urlShortener'){
                    sh 'dotnet test --logger "html;LogFileName=TestResults.html"'
                }
            }
        }

        stage('Build images'){
            agent any
            environment {
                TAG = '1.0.0'
            }
            steps{
                dir('urlShortener'){
                    sh 'docker compose build'
                }
            }
        }
    }
}