pipeline {
    agent any
    stages {
        stage('Run Tests'){
            agent { docker {image 'mcr.microsoft.com/dotnet/sdk:8.0'}}
            steps{
                sh 'apt-get update \
                    && apt-get install -y build-essential \
                    && echo "Done installing dependencies"'
                    
                dir('urlShortener'){
                    sh 'make test'
                }
            }
        }

        stage('Build images'){
            agent any
            steps{
                sh 'apt-get update \
                    && apt-get install -y build-essential \
                    && echo "Done installing dependencies"'

                dir('urlShortener'){
                    sh 'make build-images'
                }
            }
        }
    }
}