#!/bin/bash

PROJ_README_FILE=".*/README.md"

if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "${PROJ_README_FILE}"; then
    echo "[I] Project README file updated. Updating repository README.md file ..."
    ./scripts/generate-readme.sh && echo "[I] Done updating README.md" || echo "[X] Error executing post-commit script"
    git add README.md && git commit -m "Post-commit hook - Update repository README.md"
fi